'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class empresa

    '''<summary>
    '''pnl_gravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_gravar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmd_ok_gravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmd_ok_gravar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnl_obrigatório control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_obrigatório As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmd_voltar_obrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmd_voltar_obrigatorio As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnl_principal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_principal As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cs_cnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_cnpj As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_razaosocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_razaosocial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_nomefantasia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_nomefantasia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_inscricaoestadual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_inscricaoestadual As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_cnaeFiscal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_cnaeFiscal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmb_regime_tributario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_regime_tributario As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cs_im control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_im As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_telefone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_telefone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_contato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_contato As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_cep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_cep As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_endereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_endereco As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_numero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_numero As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_complemento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_complemento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_bairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_bairro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_codMunicipio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_codMunicipio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_nomemunicipio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_nomemunicipio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_uf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_uf As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cs_iest_ac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_ac As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_al control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_al As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_ap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_ap As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_am control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_am As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_ba control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_ba As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_ce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_ce As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_df control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_df As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_es control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_es As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_go control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_go As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_ma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_ma As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_mt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_mt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_ms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_ms As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_mg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_mg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_pa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_pa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_pb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_pb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_pr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_pr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_pe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_pe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_pi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_pi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_rj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_rj As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_rn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_rn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_rs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_rs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_ro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_ro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_rr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_rr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_sc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_sc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_sp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_sp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_se control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_se As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_iest_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_iest_to As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''img_logo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img_logo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''file_logo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents file_logo As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''cmd_carregar_logo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmd_carregar_logo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
