'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Grupo

    '''<summary>
    '''pnl_gravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_gravar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmd_ok_gravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmd_ok_gravar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnl_obrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_obrigatorio As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmd_voltar_obrigatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmd_voltar_obrigatorio As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnl_principal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_principal As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cs_codigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_codigo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_descricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_descricao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmd_gravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmd_gravar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmd_deletar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmd_deletar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmd_limpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmd_limpar As Global.System.Web.UI.WebControls.Button
End Class
