'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class teste

    '''<summary>
    '''cs_cnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_cnpj As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_razaosocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_razaosocial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_nomefantasia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_nomefantasia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_inscricaoestadual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_inscricaoestadual As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_IE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_IE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_cnaeFiscal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_cnaeFiscal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_regimeTributario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_regimeTributario As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cs_cep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_cep As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_endereco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_endereco As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_numero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_numero As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_complemento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_complemento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_bairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_bairro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_codMunicipio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_codMunicipio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_nomemunicipio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_nomemunicipio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_uf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_uf As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cs_codPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_codPais As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_nomePais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_nomePais As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cs_telefone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cs_telefone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button
End Class
